### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by Zoher15**
Fixes the issue #21

### CODE REVIEW

**Comment by Zoher15** [comment]
Hi @goodbai-nlp, can you complete this pull request?

**Comment by goodbai-nlp** [comment]
Declined. This modification broke the code's compatibility.

**Comment by Zoher15** [comment]
Without this merge, the code doesn't work anyway. Can you specify the compatibility that broke?

**Comment by goodbai-nlp** [comment]
The code can work fine on my computer, and other people have also found it to be operational. You'd better to check your own setting.

**Comment by Zoher15** [comment]
I have done this multiple times @goodbai-nlp . I deleted/re-cloned the repo, and re-installed the conda environment. Same issue as the OS Error in #21

**Pull request closed without merging**
